server:
  port: 8087

spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: labdhidoshi323@gmail.com
    password: khklzhulifozzbtc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
